(./main.tex
    LaTeX2e 
    <2022-11-01>
    L3 programming layer 
    <2022-11-02> 
    (latex/memoir/memoir.cls
        Document Class: memoir 2022/07/29 v3.7r configurable book, report, article document class
        (latex/etoolbox/etoolbox.sty) 
        (generic/iftex/iftex.sty) 
        (latex/memoir/mem11.clo) 
        (latex/tools/array.sty) 
        (latex/tools/dcolumn.sty) 
        (latex/tools/delarray.sty) 
        (latex/tools/tabularx.sty) 
        (latex/textcase/textcase.sty)
    ) 
    (./totex/Settings.tex 
        (latex/base/fontenc.sty) 
        (latex/base/inputenc.sty) 
        (latex/newunicodechar/newunicodechar.sty) 
        (latex/silence/silence.sty) 
        (latex/pdfpages/pdfpages.sty 
            (latex/base/ifthen.sty) 
            (latex/tools/calc.sty) 
            (latex/eso-pic/eso-pic.sty 
                (latex/graphics/keyval.sty) 
                (latex/xcolor/xcolor.sty 
                    (latex/graphics-cfg/color.cfg) 
                    (latex/graphics-def/pdftex.def) 
                    (latex/graphics/mathcolor.ltx)
                )
            ) 
            (latex/graphics/graphicx.sty 
                (latex/graphics/graphics.sty 
                    (latex/graphics/trig.sty) 
                    (latex/graphics-cfg/graphics.cfg)
                )
            ) 
            (latex/pdfpages/pppdftex.def)
        ) 
        (latex/pgf/frontendlayer/tikz.sty 
            (latex/pgf/basiclayer/pgf.sty 
                (latex/pgf/utilities/pgfrcs.sty 
                    (generic/pgf/utilities/pgfutil-common.tex 
                        (generic/pgf/utilities/pgfutil-common-lists.tex)
                    ) 
                    (generic/pgf/utilities/pgfutil-latex.def) 
                    (generic/pgf/utilities/pgfrcs.code.tex 
                        (generic/pgf/pgf.revision.tex)
                    )
                ) 
                (latex/pgf/basiclayer/pgfcore.sty 
                    (latex/pgf/systemlayer/pgfsys.sty 
                        (generic/pgf/systemlayer/pgfsys.code.tex 
                            (generic/pgf/utilities/pgfkeys.code.tex 
                                (generic/pgf/utilities/pgfkeysfiltered.code.tex)
                            ) 
                            (generic/pgf/systemlayer/pgf.cfg) 
                            (generic/pgf/systemlayer/pgfsys-pdftex.def 
                                (generic/pgf/systemlayer/pgfsys-common-pdf.def)
                            )
                        ) 
                        (generic/pgf/systemlayer/pgfsyssoftpath.code.tex) 
                        (generic/pgf/systemlayer/pgfsysprotocol.code.tex)
                    ) 
                    (generic/pgf/basiclayer/pgfcore.code.tex 
                        (generic/pgf/math/pgfmath.code.tex 
                            (generic/pgf/math/pgfmathcalc.code.tex 
                                (generic/pgf/math/pgfmathutil.code.tex) 
                                (generic/pgf/math/pgfmathparser.code.tex) 
                                (generic/pgf/math/pgfmathfunctions.code.tex 
                                    (generic/pgf/math/pgfmathfunctions.basic.code.tex) 
                                    (generic/pgf/math/pgfmathfunctions.trigonometric.code.tex) 
                                    (generic/pgf/math/pgfmathfunctions.random.code.tex) 
                                    (generic/pgf/math/pgfmathfunctions.comparison.code.tex) 
                                    (generic/pgf/math/pgfmathfunctions.base.code.tex) 
                                    (generic/pgf/math/pgfmathfunctions.round.code.tex) 
                                    (generic/pgf/math/pgfmathfunctions.misc.code.tex) 
                                    (generic/pgf/math/pgfmathfunctions.integerarithmetics.code.tex)
                                )
                            ) 
                            (generic/pgf/math/pgfmathfloat.code.tex)
                        ) 
                        (generic/pgf/math/pgfint.code.tex) 
                        (generic/pgf/basiclayer/pgfcorepoints.code.tex) 
                        (generic/pgf/basiclayer/pgfcorepathconstruct.code.tex) 
                        (generic/pgf/basiclayer/pgfcorepathusage.code.tex) 
                        (generic/pgf/basiclayer/pgfcorescopes.code.tex) 
                        (generic/pgf/basiclayer/pgfcoregraphicstate.code.tex) 
                        (generic/pgf/basiclayer/pgfcoretransformations.code.tex) 
                        (generic/pgf/basiclayer/pgfcorequick.code.tex) 
                        (generic/pgf/basiclayer/pgfcoreobjects.code.tex) 
                        (generic/pgf/basiclayer/pgfcorepathprocessing.code.tex) 
                        (generic/pgf/basiclayer/pgfcorearrows.code.tex) 
                        (generic/pgf/basiclayer/pgfcoreshade.code.tex) 
                        (generic/pgf/basiclayer/pgfcoreimage.code.tex 
                            (generic/pgf/basiclayer/pgfcoreexternal.code.tex)
                        ) 
                        (generic/pgf/basiclayer/pgfcorelayers.code.tex) 
                        (generic/pgf/basiclayer/pgfcoretransparency.code.tex) 
                        (generic/pgf/basiclayer/pgfcorepatterns.code.tex) 
                        (generic/pgf/basiclayer/pgfcorerdf.code.tex)
                    )
                ) 
                (generic/pgf/modules/pgfmoduleshapes.code.tex) 
                (generic/pgf/modules/pgfmoduleplot.code.tex) 
                (latex/pgf/compatibility/pgfcomp-version-0-65.sty) 
                (latex/pgf/compatibility/pgfcomp-version-1-18.sty)
            ) 
            (latex/pgf/utilities/pgffor.sty 
                (latex/pgf/utilities/pgfkeys.sty 
                    (generic/pgf/utilities/pgfkeys.code.tex)
                )
                (latex/pgf/math/pgfmath.sty 
                    (generic/pgf/math/pgfmath.code.tex)
                ) 
                (generic/pgf/utilities/pgffor.code.tex 
                    (generic/pgf/math/pgfmath.code.tex)
                )
            ) 
            (generic/pgf/frontendlayer/tikz/tikz.code.tex 
                (generic/pgf/libraries/pgflibraryplothandlers.code.tex) 
                (generic/pgf/modules/pgfmodulematrix.code.tex) 
                (generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopaths.code.tex)
            )
        ) 
        (latex/placeins/placeins.sty) 
        (latex/printlen/printlen.sty) 
        (latex/caption/subcaption.sty 
            (latex/caption/caption.sty 
                (latex/caption/caption3.sty 
                    (latex/caption/caption-memoir.sto)
                )
            )
        ) 
        (latex/psnfss/palatino.sty) 
        (latex/microtype/microtype.sty 
            (latex/microtype/microtype-pdftex.def) 
            (latex/microtype/microtype.cfg)
        ) 
        (latex/capt-of/capt-of.sty) 
        (latex/tools/longtable.sty) 
        (latex/ltablex/ltablex.sty) 
        (latex/multirow/multirow.sty) 
        (latex/makecell/makecell.sty) 
        (latex/relsize/relsize.sty) 
        (latex/amsmath/amsmath.sty
            For additional information on amsmath, use the '?' option.
            (latex/amsmath/amstext.sty 
                (latex/amsmath/amsgen.sty)
            ) 
            (latex/amsmath/amsbsy.sty) 
            (latex/amsmath/amsopn.sty)
        ) 
        (latex/amsfonts/amssymb.sty 
            (latex/amsfonts/amsfonts.sty)
        ) 
        (latex/tools/bm.sty) 
        (latex/siunitx/siunitx.sty) 
        (latex/geometry/geometry.sty 
            (generic/iftex/ifvtex.sty)
        ) 
        (latex/pdflscape/pdflscape.sty 
            (latex/pdflscape/pdflscape-nometadata.sty 
                (latex/graphics/lscape.sty)
            )
        ) 
        (latex/tools/xspace.sty) 
        (latex/biblatex/biblatex.sty 
            (generic/pdftexcmds/pdftexcmds.sty 
                (generic/infwarerr/infwarerr.sty) 
                (generic/ltxcmds/ltxcmds.sty)
            ) 
            (latex/kvoptions/kvoptions.sty 
                (latex/kvsetkeys/kvsetkeys.sty)
            ) 
            (latex/logreq/logreq.sty 
                (latex/logreq/logreq.def)
            ) 
            (latex/url/url.sty) 
            (latex/biblatex/blx-dm.def) 
            (latex/biblatex/blx-compat.def) 
            (latex/biblatex/biblatex.def) 
            (latex/biblatex/bbx/alphabetic.bbx 
                (latex/biblatex/bbx/standard.bbx)
            ) 
            (latex/biblatex/cbx/alphabetic.cbx) 
            (latex/biblatex/biblatex.cfg) 
            (latex/l3kernel/expl3.sty 
                (latex/l3backend/l3backend-pdftex.def)
            ) 
            (latex/biblatex/blx-case-expl3.sty 
                (latex/l3packages/xparse/xparse.sty)
            )
        ) 
        (latex/xurl/xurl.sty
            xurl: Set penalties for biblatex
            ) 
        (latex/tools/varioref.sty) 
        (latex/hyperref/hyperref.sty 
            (generic/kvdefinekeys/kvdefinekeys.sty) 
            (generic/pdfescape/pdfescape.sty) 
            (latex/hycolor/hycolor.sty) 
            (latex/letltxmacro/letltxmacro.sty) 
            (latex/auxhook/auxhook.sty) 
            (latex/hyperref/nameref.sty 
                (latex/refcount/refcount.sty) 
                (generic/gettitlestring/gettitlestring.sty)
            ) 
            (latex/hyperref/pd1enc.def) 
            (generic/intcalc/intcalc.sty) 
            (generic/etexcmds/etexcmds.sty) 
            (latex/hyperref/puenc.def) 
            (generic/bitset/bitset.sty 
                (generic/bigintcalc/bigintcalc.sty)
            ) 
            (latex/base/atbegshi-ltx.sty)
        ) 
        (latex/hyperref/hpdftex.def 
            (latex/base/atveryend-ltx.sty) 
            (latex/rerunfilecheck/rerunfilecheck.sty 
                (generic/uniquecounter/uniquecounter.sty)
            )
        ) 
        (latex/memoir/memhfixc.sty
            Redoing nameref's sectioning
            Redoing nameref's label
            ) 
        (latex/bookmark/bookmark.sty 
            (latex/bookmark/bkm-pdftex.def)
        ) 
        (latex/cleveref/cleveref.sty)
    ) 
    (./totex/Commands.tex) 
    (latex/psnfss/t1ppl.fd) 
    (./main.aux) 
    (latex/epstopdf-pkg/epstopdf-base.sty 
        (latex/grfext/grfext.sty) 
        (latex/latexconfig/epstopdf-sys.cfg)
    ) 
    (latex/caption/ltcaption.sty) 
    (latex/microtype/mt-ppl.cfg)
    *geometry* driver: auto-detecting
    *geometry* detected driver: pdftex
    (latex/biblatex/lbx/english.lbx) 
    (./main.bbl) 
    (latex/base/t1cmss.fd) 
    (latex/microtype/mt-cmr.cfg) 
    (latex/amsfonts/umsa.fd) 
    (latex/microtype/mt-msa.cfg) 
    (latex/amsfonts/umsb.fd) 
    (latex/microtype/mt-msb.cfg) 
    (latex/base/ts1cmss.fd) 
    [1
        {c:/TinyTeX/texmf-var/fonts/map/pdftex/updmap/pdftex.map} 
        <./figs//diagram_Connectivity↔Activity.png>
    ] 
    [2 
        <./figs//diagram_Nto1.png>
    ] 
    [3 
        <./figs//STA_height_shuffle_test.png>
    ] 
    [4 
        <./figs//2022-07-15__Network_plus_noise_19_0.png> 
        <./figs//2022-07-15__Network_plus_noise_20_0.png>
    ] 
    (./main.aux) 
)
{c:/TinyTeX/texmf-dist/fonts/enc/dvips/cm-super/cm-super-t1.enc}
{c:/TinyTeX/texmf-dist/fonts/enc/dvips/cm-super/cm-super-ts1.enc}
{c:/TinyTeX/texmf-dist/fonts/enc/dvips/base/8r.enc}
<c:/TinyTeX/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb>
<c:/TinyTeX/texmf-dist/fonts/type1/public/cm-super/sfsi1000.pfb>
<c:/TinyTeX/texmf-dist/fonts/type1/public/cm-super/sfsi1095.pfb>
<c:/TinyTeX/texmf-dist/fonts/type1/public/cm-super/sfss1095.pfb>
<c:/TinyTeX/texmf-dist/fonts/type1/public/cm-super/sfsx1095.pfb>
<c:/TinyTeX/texmf-dist/fonts/type1/public/cm-super/sfsx1440.pfb>
<c:/TinyTeX/texmf-dist/fonts/type1/urw/palatino/uplr8a.pfb>